### ISSUE TITLE
[BUG]Client required

### ISSUE THREAD

**Issue by zyxkad** [kosma/mysql-jdbc-mod#1]
This mod actually **needn't client support**. It just like a library.

But if I use it on the *server side*, I **must** install this mod on the *client side*  
**Even if this mod do nothing**

**Comment by kosma** [comment]
What platform and Minecraft version?

**Comment by zyxkad** [comment]
Forge 1.12.2

**Comment by zyxkad** [comment]
Hello? @kosma

**Comment by kosma** [comment]
Please try with this release:

https://github.com/kosma/mysql-jdbc-mod/releases/tag/8.0.30%2B20220916

**Comment by zyxkad** [comment]
I'm sorry my server has closed, but if I have time I will try.  
If you already tested it, you can close it as completed

**Comment by kosma** [comment]
Okay! I close the issue then.
